#requires -version 5
<#
  build.ps1 — one command to produce the final OptiGuard installer.

  1. Reads version.json (the single source of truth for the version number)
  2. Writes build/Version.props so both .csproj files pick up that version
  3. Patches src/app.manifest's assemblyIdentity version to match
  4. Builds src/OptiGuard.csproj (Release) — the main app
  5. Builds Setup.csproj (Release) — the installer, which embeds the exe from step 4
  6. Copies the built installer to the project root as OptiGuard-Setup-<version>.exe
     (and removes any stale installer file from a previous version, so the root
     never ends up with two installers side by side)

  Run from the project root:  .\build.ps1
#>

$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot

Write-Host "==> Reading version.json..." -ForegroundColor Cyan
$versionInfo = Get-Content version.json -Raw | ConvertFrom-Json
$version = $versionInfo.version
Write-Host "    Version: $version"

Write-Host "==> Writing build/Version.props..." -ForegroundColor Cyan
@"
<Project>
  <!--
    Generated by build.ps1 from version.json. Do not edit by hand.
    version.json is the single source of truth; this file just makes that
    value visible to MSBuild (which can't parse JSON on its own).
  -->
  <PropertyGroup>
    <Version>$version</Version>
  </PropertyGroup>
</Project>
"@ | Set-Content build\Version.props -Encoding UTF8

Write-Host "==> Patching src/app.manifest version..." -ForegroundColor Cyan
$manifestPath = "src\app.manifest"
$manifest = Get-Content $manifestPath -Raw
$manifest = $manifest -replace 'assemblyIdentity version="[\d.]+"', "assemblyIdentity version=`"$version.0`""
Set-Content $manifestPath $manifest -Encoding UTF8 -NoNewline

Write-Host "==> Building main app (src/OptiGuard.csproj)..." -ForegroundColor Cyan
dotnet build src\OptiGuard.csproj -c Release -v minimal
if ($LASTEXITCODE -ne 0) { throw "Main app build failed." }

$mainExe = "src\bin\Release\net48\OptiGuard.exe"
if (-not (Test-Path $mainExe)) { throw "Expected build output not found: $mainExe" }

Write-Host "==> Building installer (Setup.csproj)..." -ForegroundColor Cyan
dotnet build Setup.csproj -c Release -v minimal
if ($LASTEXITCODE -ne 0) { throw "Installer build failed." }

$builtInstaller = "bin\Release\net48\OptiGuard-Setup.exe"
if (-not (Test-Path $builtInstaller)) { throw "Expected build output not found: $builtInstaller" }

$finalName = "OptiGuard-Setup-$version.exe"
Write-Host "==> Removing any stale installer file(s) from previous versions..." -ForegroundColor Cyan
Get-ChildItem -Path . -Filter "OptiGuard-Setup-*.exe" -File | Where-Object { $_.Name -ne $finalName } | Remove-Item -Force
if (Test-Path ".\Setup-OptiGuard.exe") { Remove-Item ".\Setup-OptiGuard.exe" -Force } # old pre-4.9.0 filename

Copy-Item $builtInstaller ".\$finalName" -Force
Write-Host "==> Done." -ForegroundColor Green
Get-Item ".\$finalName" | Format-Table Name, @{Label="Size (KB)"; Expression={"{0:N0}" -f ($_.Length/1KB)}}, LastWriteTime
Write-Host "Installer ready at: $(Resolve-Path .\$finalName)" -ForegroundColor Green
